#!/bin/bash
# ============================================================
# Ujenzi Dhabiti — VPS Setup Script
# Ubuntu 22.04 / 24.04
# Run as root: bash setup-vps.sh yourdomain.com
# ============================================================

set -e

DOMAIN=${1:-"ujenzidhabiti.co.ke"}
APP_DIR="/var/www/ujenzi-dhabiti"
DB_NAME="ujenzidhabiti"
DB_USER="ujenziapp"
DB_PASS=$(openssl rand -base64 24)
NODE_VERSION="20"

echo "============================================"
echo " Ujenzi Dhabiti — VPS Setup"
echo " Domain: $DOMAIN"
echo "============================================"

# ─── System update ────────────────────────────────────────────
echo "[1/9] Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ─── Node.js ──────────────────────────────────────────────────
echo "[2/9] Installing Node.js $NODE_VERSION..."
curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
apt-get install -y -qq nodejs
node -v && npm -v

# ─── PM2 ──────────────────────────────────────────────────────
echo "[3/9] Installing PM2..."
npm install -g pm2 -q
pm2 startup systemd -u root --hp /root | tail -1 | bash

# ─── PostgreSQL ───────────────────────────────────────────────
echo "[4/9] Installing PostgreSQL 16..."
apt-get install -y -qq postgresql postgresql-contrib
systemctl enable postgresql
systemctl start postgresql

# Create DB and user
sudo -u postgres psql <<SQL
CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';
CREATE DATABASE $DB_NAME OWNER $DB_USER;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
SQL

echo ""
echo "  ✓ Database: $DB_NAME"
echo "  ✓ DB User:  $DB_USER"
echo "  ✓ DB Pass:  $DB_PASS"
echo "  → Save this password now! It won't be shown again."
echo ""

# ─── Nginx ────────────────────────────────────────────────────
echo "[5/9] Installing Nginx..."
apt-get install -y -qq nginx
systemctl enable nginx

cat > /etc/nginx/sites-available/ujenzi-dhabiti <<NGINX
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    # Increase upload size for product images
    client_max_body_size 20M;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/ujenzi-dhabiti /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

# ─── SSL (Let's Encrypt) ──────────────────────────────────────
echo "[6/9] Installing Certbot (SSL)..."
apt-get install -y -qq certbot python3-certbot-nginx
certbot --nginx -d $DOMAIN -d www.$DOMAIN --non-interactive --agree-tos -m admin@$DOMAIN
systemctl enable certbot.timer

# ─── Firewall ─────────────────────────────────────────────────
echo "[7/9] Configuring firewall..."
apt-get install -y -qq ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 'Nginx Full'
ufw --force enable

# ─── App directory ────────────────────────────────────────────
echo "[8/9] Creating app directory..."
mkdir -p $APP_DIR
cat > $APP_DIR/.env.production <<ENV
# Generated by setup-vps.sh — fill in all values before deploying
DATABASE_URL=postgresql://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME

NEXTAUTH_SECRET=$(openssl rand -base64 32)
NEXTAUTH_URL=https://$DOMAIN

RESEND_API_KEY=re_REPLACE_ME

DARAJA_CONSUMER_KEY=REPLACE_ME
DARAJA_CONSUMER_SECRET=REPLACE_ME
DARAJA_SHORTCODE=REPLACE_ME
DARAJA_PASSKEY=REPLACE_ME
DARAJA_CALLBACK_URL=https://$DOMAIN/api/payments/mpesa/callback
DARAJA_ENV=sandbox

FLUTTERWAVE_PUBLIC_KEY=FLWPUBK_TEST-REPLACE_ME
FLUTTERWAVE_SECRET_KEY=FLWSECK_TEST-REPLACE_ME
FLUTTERWAVE_WEBHOOK_SECRET=REPLACE_ME

CLOUDINARY_CLOUD_NAME=REPLACE_ME
CLOUDINARY_API_KEY=REPLACE_ME
CLOUDINARY_API_SECRET=REPLACE_ME

PLATFORM_FEE_PERCENT=3
ENV

chmod 600 $APP_DIR/.env.production
echo "  ✓ .env.production created at $APP_DIR/.env.production"

# ─── Backup dependencies ──────────────────────────────────────
echo "[9/9] Installing backup tools..."
apt-get install -y -qq awscli  # used for Backblaze B2 (S3-compatible) or DO Spaces
cp $(dirname "$0")/backup.sh /etc/cron.daily/ujenzi-backup
chmod +x /etc/cron.daily/ujenzi-backup

# ─── Done ─────────────────────────────────────────────────────
echo ""
echo "============================================"
echo " Setup complete!"
echo "============================================"
echo ""
echo " Next steps:"
echo "   1. Fill in /var/www/ujenzi-dhabiti/.env.production"
echo "   2. Copy your app: scp -r . root@YOUR_VPS:$APP_DIR"
echo "   3. cd $APP_DIR && npm install && npm run build"
echo "   4. npm run db:migrate"
echo "   5. npm run db:seed"
echo "   6. pm2 start npm --name ujenzi-dhabiti -- start"
echo "   7. pm2 save"
echo ""
echo " Your site will be live at: https://$DOMAIN"
echo ""
